### ISSUE TITLE
People link failure from image section

### ISSUE THREAD

**Issue by ImKeTT** [z1514/OpenRichpedia#1]
Thanks for providing such a great work. Current [People](https://pan.baidu.com/s/1tUnmlA7Fb90pPZwhxy-jow) link from image section in Baidu Drive doesn't work. It would be very helpful to update the link. Thanks !

**Comment by z1514** [comment]
Hello, thank you for your feedback. It seems Baidu Drvie banned this file and tagged it as illegal, so I can not generate a new link.  I will try to solve this problem. Thanks.

**Comment by z1514** [comment]
Hello, sorry for the delay. You can use the updated link to download the dataset: https://pan.baidu.com/s/1GaJwuByW4oMhLCgfjHQULg. The code is 0000 and the password is richpedia. If you meet any questions, please let me know.

**Comment by ImKeTT** [comment]
yes its a valid link, thanks a lot!
